python-server/mysite/fileupload/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
  url(r'^$', views.upload),
  url(r'upload$', views.upload, name='upload'),
]

python-server/mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'tempserver/', include('tempserver.urls', namespace='tempserver')),
    url(r'fileupload/', include('fileupload.urls', namespace='fileupload')),
]

python-server/mysite/tempserver/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.temp_page),
    url(r'temp_page$', views.temp_page),
    url(r'get_temp$', views.get_temp_req),
]

python-server/mysite/fileupload/models.py
from django.db import models

# Create your models here.

python-server/mysite/fileupload/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.http import require_http_methods
from django.core.files.move import file_move_safe
from django.forms import Form
from django.forms import fields

UPLOAD_TO_DIR = "/home/dlila/repos/public/python-server/mysite/fileupload/uploaded_files/"

class UploadForm(Form):
  ff = fields.FileField(label='select a file')

def handle_file(src):
  with open(UPLOAD_TO_DIR + src.name, 'w+') as dest:
    for chunk in src.chunks():
      dest.write(chunk)

@require_http_methods(['GET', 'POST'])
def upload(req):
  if req.method == 'POST':
    form = UploadForm(req.POST, req.FILES)
    if form.is_valid():
      f = req.FILES['ff']
      handle_file(f)
      # TODO(dlila): handle failures in handle_file
      return render(req, 'fileupload/uploadsuccess.html', {'file_name' : f.name})
  else:
    form = UploadForm()
  return render(req, 'fileupload/fileupload.html', {'form' : form})

python-server/mysite/tempserver/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import RequestContext
from django.views.decorators.http import require_GET

@require_GET
def temp_page(req):
  context = RequestContext(req, {'temperature': get_temp()})
  return render(req, 'tempserver/temperature.html', context)

@require_GET
def get_temp_req(req):
  return HttpResponse(get_temp())

def get_temp():
  # TODO(dlila): implement this properly
  return "22.1"

# Create your views here.

python-server/mysite/fileupload/templates/fileupload/fileupload.html
<!DOCTYPE html>
<html>
<head>
  <title>Upload file.</title>
</head>

<body> 
  <form action="{% url 'fileupload:upload' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
</body>
</html>

python-server/mysite/fileupload/templates/fileupload/uploadsuccess.html
<!DOCTYPE html>
<html>
<head>
  <title>Upload Done.</title>
</head>

<body> 
  <p> Done uploading {{ file_name }}. </p>
</body>
</html>

python-server/mysite/tempserver/templates/tempserver/temperature.html
<!DOCTYPE html>
<html>
<head>
  <title>Page Title</title>
  <script type="text/javascript">
  function get_temp(cb) {
    var req = new XMLHttpRequest()
    req.onload = function() {
      cb(this.responseText)
    }
    req.open('get', 'get_temp', true)
    req.send()
  }
  function set_temp(t) {
    document.getElementById("temp").innerText = t
  }
  </script>
</head>

<body> 
  <p>Temperature is <span id="temp"> {{ temperature }} </span> degrees celcius </p>
</body>

<script type='text/javascript'>
  get_temp(set_temp)
  // This sucks. Temperatures don't change this often. TODO(dlila): don't poll.
  // Just make these calls blocking. If the server thinks the temperature has
  // changed by a wide enough margin, it will just return the new value. This
  // will give us both low update latency AND it will not be wasteful.
  // TODO(dlila): add https and authentication to this server.
  // TODO(dlila): android client.
  window.setInterval(function() { get_temp(set_temp) }, 1500)
</script>
</html>